diff --git a/Dockerfile b/Dockerfile
index 28bf9db..93b1c96 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,7 +6,8 @@ FROM caddy:${CADDY_VERSION}-builder AS builder
 RUN xcaddy build \
     --with github.com/caddy-dns/cloudflare \
     --with github.com/WeidiDeng/caddy-cloudflare-ip \
-    --with github.com/fvbommel/caddy-combine-ip-ranges
+    --with github.com/fvbommel/caddy-combine-ip-ranges \
+    --with github.com/greenpau/caddy-security
 
 # Final stage
 FROM caddy:${CADDY_VERSION}
